# Generated by Django 6.0.3 on 2026-03-19 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activitylog'),
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='flats.flat'),
        ),
    ]
