# Generated by Django 6.0.3 on 2026-03-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='resident_proofs/address/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='resident_proofs/id/'),
        ),
    ]
