# Generated by Django 6.0.3 on 2026-03-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('floor', models.IntegerField()),
            ],
        ),
    ]
