# Generated by Django 6.0.3 on 2026-03-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'ordering': ['block', 'number']},
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('block', 'number')},
        ),
    ]
