# Generated by Django 6.0.3 on 2026-03-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='vehicle_registration_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
